# devices
CONFIG_EN_GPIO_LED0=y
CONFIG_EN_GPIO_SW0=y
CONFIG_EN_DEV_LORA=y
CONFIG_EN_DEV_DISPLAY=y
CONFIG_EN_DEV_SDHC=y
CONFIG_EN_DEV_I2S=y
CONFIG_EN_DEV_UFIREBIRDII=y
CONFIG_EN_DEV_CAN0=y
CONFIG_EN_DEV_CAN1=y

# ufirebirdii reqs
CONFIG_UFIREBIRDII=y
CONFIG_UC6580=y
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=2048
CONFIG_PICOLIBC_IO_FLOAT=y

# CAN reqs
CONFIG_CAN=y
CONFIG_CAN_SHELL=y